site_name: "Benutzerhandbuch"
site_url: https://docs.admin.digital
docs_dir: content
site_description: "Das Benutzerhandbuch für die admin.digital Plattform. Hier findest du Anleitungen, Tipps und Informationen zur Nutzung der verschiedenen Module und Funktionen."

theme:
  name: material
  language: de
  logo: img/logo.svg
  favicon: img/favicon.svg
  custom_dir: overrides
  font: false
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Dunkelmodus aktivieren
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Hellmodus aktivieren
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate

plugins:
  - search:
      lang:
        - de
        - en
  - tags

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/custom.css
  - stylesheets/extra.css

extra_javascript:
  - javascripts/custom.js

nav:
  - Startseite: index.md
  - Erste Schritte:
      - erste-schritte/index.md
  - Services:
      - services/index.md
      - Gemeindeportal: services/gemeindeportal/index.md
      - Publikationen für Wahlen und Abstimmungen: services/publikationen-wahlen-abstimmungen/index.md
      - Buchungsplattform Ferienangebote (Pro Juventute): services/feriennet/index.md
      - Koordination Übersetzungsdienst:
        - services/dolmetschkoordination/index.md
        - Zeiterfassung: services/dolmetschkoordination/zeiterfassung.md
      - Staatskalender: services/staatskalender/index.md
      - Kursverwaltung: services/kursverwaltung/index.md
      - Planauflage Baugesuche: services/planauflage-baugesuche/index.md
      - Versammlungen (Landsgemeinde): services/versammlungen-landsgemeinde/index.md
      - Datenportal Abstimmungen (Swissvotes): services/datenportal-abstimmungen-swissvotes/index.md
      - Intranet: services/intranet/index.md
  - Module:
      - module/index.md
      - Formulare:
        - module/formulare/index.md
        - Beispiele Formcode: module/formulare/beispiele.md
      - Online-Schalter: module/online-schalter/index.md
      - Umfragen: module/umfragen/index.md
      - Link-Prüfung: module/link-pruefung/index.md
      - Online Bezahlung: module/online-bezahlung/index.md
      - Reservationen: module/reservationen/index.md
      - Themen und News: module/themen-und-news/index.md
      - E-Mail Newsletter:
        - module/e-mail-newsletter/index.md
        - Newsletter erstellen und verschicken: module/e-mail-newsletter/erstellen-und-verschicken.md
      - Benutzerverwaltung: module/benutzerverwaltung/index.md
      - Kundenlogin (Password Less): module/kundenlogin-password-less/index.md
      - Service Ticketing: module/service-ticketing/index.md
      - Chat: module/chat/index.md
      - Chatbot (RAG) (BETA): module/chatbot/index.md
      - Schnittstelle GEVER: module/gever/index.md
      - Ratsinformationssystem (RIS): module/ratsinformationssystem/index.md
      - Digitale Siegel: module/digitale-siegel/index.md
      - Datensparsamkeit: module/datensparsamkeit/index.md
      - Analytics: module/analytics/index.md
      - Open Government Data (ODG): module/open-government-data/index.md
      - Headless CMS: module/headless-cms/index.md
      - Karten: module/karten/index.md
      - Personenverzeichnis: module/personenverzeichnis/index.md
      - Veranstaltungskalender: module/veranstaltungskalender/index.md
      - Verzeichnisse: module/verzeichnisse/index.md
      - Fotoalben: module/fotoalben/index.md
      - Suche: module/suche/index.md
  - Neuerungen: neuerungen/index.md
  - FAQ:
      - faq/index.md
  - Kontakt & Support: kontakt.md
